### PR TITLE
Add some builder-like support to appropriate classes

### PR DESCRIPTION
**Pull request by er1c**
Hi,

This might break some binary compatibility.  If you prefer I can add separate `*Builder` classes (e.g.  I can add a `HttpProxyServerConfigBuilder.java`)

Thank you for your great work!

Best Regards,

Eric

### CODE REVIEW

**Comment by monkeyWie** [comment]
Thank for your PR, this is a break change, I will merge it at major version change.

**Comment by er1c** [comment]
> Thank for your PR, this is a break change, I will merge it at major version change.

Yes, I make sure to mention that!

What do you think about adding a `HttpProxyServerConfigBuilder` to maintain binary compatibility?

**Comment by monkeyWie** [comment]
I think it's OK that add a `Builder` class, so if we have a `Builder` class, it can replace this PR.

**Comment by er1c** [comment]
@monkeyWie I updated this PR to include the `Builder` without changing the binary-compatability

**Comment by monkeyWie** [comment]
Nice!

**Pull request merged**
